name = "LogCompose"
uuid = "8416b438-731e-11ea-2421-05f642269042"
keywords = ["configure", "compose", "logging", "logger"]
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
license = "MIT"
desc = "Compose loggers and logger ensembles declaratively using configuration files"
version = "0.2.1"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
